[build]
  command = "bun run build:netlify"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/favicon.ico"
  to = "/.netlify/functions/api/favicon.ico" 
  status = 200 
  force = true

[[redirects]]
  from = "/swagger-output"
  to = "/.netlify/functions/api/swagger-output" 
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health" 
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/health"
  to = "/.netlify/functions/api/health" 
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/:splat" 
  status = 200
  force = true

[[redirects]]
  from = "/reference/"
  to = "/.netlify/functions/api/reference/" 
  status = 200
  force = true

[[redirects]]
  from = "/reference/*"
  to = "/.netlify/functions/api/:splat" 
  status = 200
  force = true
