name: Beehive Backend CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  DATABASE_URL: mongodb://localhost:27017/beehive_ci_test_db?replicaSet=rs0
  JWT_SECRET: ${{ secrets.JWT_SECRET_CI }}
  NODE_ENV: test
  LOG_LEVEL: warn
  BCRYPT_SALT_ROUNDS: 4

jobs:
  lint_and_format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome CI Checks (Lint & Format)
        run: biome ci --config-path ./biome.json --organize-imports-enabled false .

  build_application:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint_and_format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install project dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bun run db:generate

      - name: Run build script
        run: bun run build

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint_and_format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install project dependencies
        run: bun install

      - name: Run Unit Tests
        run: bun run test:unit

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint_and_format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Start MongoDB with Replica Set
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: "latest"
          mongodb-replica-set: rs0

      - name: Install project dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bun run db:generate

      - name: Generate Swagger Documentation
        run: bun run swagger:generate

      - name: Run Integration Tests
        run: bun run test:integration
        env:
          DATABASE_URL: mongodb://localhost:27017/beehive_ci_test_db?replicaSet=rs0
